# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0003_auto_20151221_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
