# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0004_auto_20161027_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='exception',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
